# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Randgen < Formula
  desc "RandGen is a simple CLI tool to generate random data of a given size."
  homepage "https://dev.shib.me/randgen"
  version "1.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shibme/randgen/releases/download/v1.0.2/randgen_darwin_amd64.zip"
      sha256 "4c03b80382e2928cdd60a935d7d9ec00ee4f3168c600043de72d986ff3cbcac4"

      def install
        bin.install "randgen"
        generate_completions_from_executable(bin/"randgen","completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shibme/randgen/releases/download/v1.0.2/randgen_darwin_arm64.zip"
      sha256 "1e5267f327fda313831fadf9c0a1a08165b97a6950c723c7aafae0abc10401cb"

      def install
        bin.install "randgen"
        generate_completions_from_executable(bin/"randgen","completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/shibme/randgen/releases/download/v1.0.2/randgen_linux_amd64.zip"
      sha256 "ecb0131b2e7b57cbc0aee0eef9aecb5da05ec09099791a445e2279d3092f6737"
      def install
        bin.install "randgen"
        generate_completions_from_executable(bin/"randgen","completion")
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/shibme/randgen/releases/download/v1.0.2/randgen_linux_arm.zip"
      sha256 "1903c535045803c7bdcf2af3d59c045aaca4341cff53b3d69f5c9f5bf8420100"
      def install
        bin.install "randgen"
        generate_completions_from_executable(bin/"randgen","completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shibme/randgen/releases/download/v1.0.2/randgen_linux_arm64.zip"
      sha256 "09bcb4cb01ccc92138a19f4b45b382753c10d6b846aadbcddf772f6215aff8ce"
      def install
        bin.install "randgen"
        generate_completions_from_executable(bin/"randgen","completion")
      end
    end
  end
end
