# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Randgen < Formula
  desc "RandGen is a simple CLI tool to generate random data of a given size."
  homepage "https://dev.shib.me/randgen"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shibme/randgen/releases/download/v1.0.1/randgen_darwin_amd64.zip"
      sha256 "7e90b72f74a38ecf2d7f085bd1846afe2ad7d2d3806184099fe6c80b0c011b5a"

      def install
        bin.install "randgen"
        generate_completions_from_executable(bin/"randgen","completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shibme/randgen/releases/download/v1.0.1/randgen_darwin_arm64.zip"
      sha256 "c931f5469752ec38be24f03fd5f2ea78f3fad336ac28a79677fce6cda17bcd7c"

      def install
        bin.install "randgen"
        generate_completions_from_executable(bin/"randgen","completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/shibme/randgen/releases/download/v1.0.1/randgen_linux_amd64.zip"
      sha256 "3f8468ab74c9e594a9bddc67ca1dbac9398e2176e9e1ea47e571b7f9ad30ecc1"
      def install
        bin.install "randgen"
        generate_completions_from_executable(bin/"randgen","completion")
      end
    end
    if Hardware::CPU.arm? and !Hardware::CPU.is_64_bit?
      url "https://github.com/shibme/randgen/releases/download/v1.0.1/randgen_linux_arm.zip"
      sha256 "eea9705c99a18d1b7673acc06bf8bed15333cff543108809d0b85aea6afc7b63"
      def install
        bin.install "randgen"
        generate_completions_from_executable(bin/"randgen","completion")
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/shibme/randgen/releases/download/v1.0.1/randgen_linux_arm64.zip"
      sha256 "90eac9df5955dd9d9b03095ec720c84bc84a6ff9934ad4d5d73792848f9d5ddf"
      def install
        bin.install "randgen"
        generate_completions_from_executable(bin/"randgen","completion")
      end
    end
  end
end
