# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Randgen < Formula
  desc "RandGen is a simple CLI tool to generate random data of a given size."
  homepage "https://dev.shib.me/randgen"
  version "1.0.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/shibme/randgen/releases/download/v1.0.0/randgen_darwin_amd64.zip"
      sha256 "7b84e2b3e46222869d808be1308edf87f4593f93bd062e54cccd961402513f5f"

      def install
        bin.install "randgen"
      end
    end
    on_arm do
      url "https://github.com/shibme/randgen/releases/download/v1.0.0/randgen_darwin_arm64.zip"
      sha256 "28ca13c221b7154ade69d3be9a3e5b61be136818814a01121497da615aaf55b7"

      def install
        bin.install "randgen"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/shibme/randgen/releases/download/v1.0.0/randgen_linux_amd64.zip"
        sha256 "4d3b0f0d1705bfd1936cfff070e515a2f79981f481ab079e0cfc28d681a8d89b"

        def install
          bin.install "randgen"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/shibme/randgen/releases/download/v1.0.0/randgen_linux_arm.zip"
        sha256 "0c0131a8794e689498d54625ad4aa8d7d6c084f9a7037af1224c79bd0ee5f253"

        def install
          bin.install "randgen"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/shibme/randgen/releases/download/v1.0.0/randgen_linux_arm64.zip"
        sha256 "a0d2634fd36b7c16bd83bb96ea84e3fecdad023de64e507124fd79f9f0fb318b"

        def install
          bin.install "randgen"
        end
      end
    end
  end
end
