# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Xipher < Formula
  desc "Xipher is a curated collection of cryptographic primitives put together to perform key/password based asymmetric encryption."
  homepage "https://dev.shib.me/xipher"
  version "1.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shibme/xipher/releases/download/v1.3.1/xipher_darwin_amd64.zip"
      sha256 "44215ceae954636ca96cbe46c16bb985cc56a30eb5360a9538456bc87b5fc63f"

      def install
        bin.install "xipher"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shibme/xipher/releases/download/v1.3.1/xipher_darwin_arm64.zip"
      sha256 "39c140104d39fbfbf20a4e6b393115dc34f007166ec844173f1e01ec645a1fd7"

      def install
        bin.install "xipher"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/shibme/xipher/releases/download/v1.3.1/xipher_linux_amd64.zip"
      sha256 "5f9c46596a95438d7a5bb29af5460a49036e3577eff78dda865cdf82529d1812"

      def install
        bin.install "xipher"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/shibme/xipher/releases/download/v1.3.1/xipher_linux_arm.zip"
      sha256 "b310f4a0c8fee1fdf9b8f89b2d4db44bd12bba2998b14b6cead58d993ace52b8"

      def install
        bin.install "xipher"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shibme/xipher/releases/download/v1.3.1/xipher_linux_arm64.zip"
      sha256 "f17d1aead4f22d44b8594b64b8f4e511f8973bd65b1903eb41e15fe2ad5a2095"

      def install
        bin.install "xipher"
      end
    end
  end
end
