# This file was generated by GoReleaser. DO NOT EDIT.
cask "xipher" do
  version "1.31.2"

  on_macos do
    on_intel do
      sha256 "a01049f064c67e37c4863b2a8f103b7e91341bdee5c6b8869ba993356e0afc45"
      url "https://github.com/shibme/xipher/releases/download/v#{version}/xipher_darwin_amd64.zip",
        verified: "github.com/shibme/xipher/"
    end
    on_arm do
      sha256 "c6aa35eb606fd3843bce9b5c58e7dc7da80b121e1d5ef41f87131b559091f709"
      url "https://github.com/shibme/xipher/releases/download/v#{version}/xipher_darwin_arm64.zip",
        verified: "github.com/shibme/xipher/"
    end
  end

  on_linux do
    on_intel do
      sha256 "17604f2c77f9337e7d007086643395da9d88925ba620aa89f9fe73b61d4e9ba7"
      url "https://github.com/shibme/xipher/releases/download/v#{version}/xipher_linux_amd64.zip",
        verified: "github.com/shibme/xipher/"
    end
    on_arm do
      sha256 "5f1f53b0b31648568d4ced180e61207f9f50e3311a4f016d59089ab3e1669826"
      url "https://github.com/shibme/xipher/releases/download/v#{version}/xipher_linux_arm64.zip",
        verified: "github.com/shibme/xipher/"
    end
  end

  name "xipher"
  desc "Xipher is a curated collection of cryptographic primitives put together to perform key/password based asymmetric encryption."
  homepage "https://xipher.org"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "xipher"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/xipher"]
    end
    system_command "/bin/mkdir", args: ["-p", "#{HOMEBREW_PREFIX}/etc/bash_completion.d"]
    system_command "/bin/mkdir", args: ["-p", "#{HOMEBREW_PREFIX}/share/zsh/site-functions"]
    system_command "/bin/mkdir", args: ["-p", "#{HOMEBREW_PREFIX}/share/fish/vendor_completions.d"]
    system_command "/bin/bash", args: ["-c", "#{staged_path}/xipher completion bash > #{HOMEBREW_PREFIX}/etc/bash_completion.d/xipher"]
    system_command "/bin/bash", args: ["-c", "#{staged_path}/xipher completion zsh > #{HOMEBREW_PREFIX}/share/zsh/site-functions/_xipher"]
    system_command "/bin/bash", args: ["-c", "#{staged_path}/xipher completion fish > #{HOMEBREW_PREFIX}/share/fish/vendor_completions.d/xipher.fish"]
  end

  # No zap stanza required

end
