# This file was generated by GoReleaser. DO NOT EDIT.
cask "xipher" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "xipher"]
    end
  end

  version "1.32.5"

  on_macos do
    on_arm do
      sha256 "9f4356378633fd0bf78d84c6870b3f243786d2ff8953b9fb01c9eab9e48d1398"
      url "https://github.com/shibme/xipher/releases/download/v#{version}/xipher_darwin_arm64.zip"
    end
    on_intel do
      sha256 "200af04bd79ab540197af99977c3c26c0ca232f8bd909b3a9d3aef561cb2f31f"
      url "https://github.com/shibme/xipher/releases/download/v#{version}/xipher_darwin_amd64.zip"
    end
  end
  on_linux do
    on_arm do
      sha256 "647e299d4ac784367c6099641a0ead11ca725060318fe5fe34429d1c4861d31e"
      url "https://github.com/shibme/xipher/releases/download/v#{version}/xipher_linux_arm64.zip"
    end
    on_intel do
      sha256 "00ad8280d8e54494c5279a2da9f9dc07281d80055191c62e5d1002861aa55cba"
      url "https://github.com/shibme/xipher/releases/download/v#{version}/xipher_linux_amd64.zip"
    end
  end

  name "xipher"
  desc "Xipher is a curated collection of cryptographic primitives put together to perform key/password based asymmetric encryption."
  homepage "https://xipher.org"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "xipher"

  generate_completions_from_executable "xipher",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required
end
