# This file was generated by GoReleaser. DO NOT EDIT.
cask "xipher" do
  version "1.32.2"

  on_macos do
    on_intel do
      sha256 "2dc68e9eb8d4a7340ff279f4b3ef40d426f705123fbf99a728fe4991363e9454"
      url "https://github.com/shibme/xipher/releases/download/v#{version}/xipher_darwin_amd64.zip",
        verified: "github.com/shibme/xipher/"
    end
    on_arm do
      sha256 "88eba04e770b1a7a87c2d48afc53cc30e5f18321b59dcfc27d0f3440255785e2"
      url "https://github.com/shibme/xipher/releases/download/v#{version}/xipher_darwin_arm64.zip",
        verified: "github.com/shibme/xipher/"
    end
  end

  on_linux do
    on_intel do
      sha256 "583635517af7340a9276a2d1c46b175bf3e5b1d991608b4562b256eedc5cd33d"
      url "https://github.com/shibme/xipher/releases/download/v#{version}/xipher_linux_amd64.zip",
        verified: "github.com/shibme/xipher/"
    end
    on_arm do
      sha256 "33d9180ba300f7f6ca209d6f458fa2eb27d195f10e9e7603b975c411a7f4017e"
      url "https://github.com/shibme/xipher/releases/download/v#{version}/xipher_linux_arm64.zip",
        verified: "github.com/shibme/xipher/"
    end
  end

  name "xipher"
  desc "Xipher is a curated collection of cryptographic primitives put together to perform key/password based asymmetric encryption."
  homepage "https://xipher.org"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "xipher"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/xipher"]
    end
    system_command "/bin/mkdir", args: ["-p", "#{HOMEBREW_PREFIX}/etc/bash_completion.d"]
    system_command "/bin/mkdir", args: ["-p", "#{HOMEBREW_PREFIX}/share/zsh/site-functions"]
    system_command "/bin/mkdir", args: ["-p", "#{HOMEBREW_PREFIX}/share/fish/vendor_completions.d"]
    system_command "/bin/bash", args: ["-c", "#{staged_path}/xipher completion bash > #{HOMEBREW_PREFIX}/etc/bash_completion.d/xipher"]
    system_command "/bin/bash", args: ["-c", "#{staged_path}/xipher completion zsh > #{HOMEBREW_PREFIX}/share/zsh/site-functions/_xipher"]
    system_command "/bin/bash", args: ["-c", "#{staged_path}/xipher completion fish > #{HOMEBREW_PREFIX}/share/fish/vendor_completions.d/xipher.fish"]
  end

  # No zap stanza required

end
